spring:
  application:
    name: eureka-consumer-feign
  rabbitmq:
    addresses: amqp://rabbitmq:5672
    username:  user
    password: 123456

server:
  port: 8184

eureka:
  client:
   serviceUrl:
    defaultZone:  http://eureka-server:8181/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always

feign:
  hystrix:
    enabled: true